---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: busybox
spec:
  schedule: '* * * * *'
  successfulJobsHistoryLimit: 10
  failedJobsHistoryLimit: 10
  jobTemplate:
    metadata:
      name: busybox
      annotations:
        ttl: 1m10s
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
            - image: busybox
              name: busybox
          restartPolicy: Never
---
apiVersion: fpetkovski.io/v1alpha1
kind: TTLPolicy
metadata:
  name: jobs-ttl-controller
spec:
  resource:
    apiVersion: batch/v1
    kind: Job
  ttlFrom: .metadata.annotations.ttl
  expirationFrom: .status.completionTime
